[package]
name = "ec"
version = "0.1.0"
authors = ["≈Åukasz Hryniuk <lukasz.hryniuk@wp.pl>"]

[dependencies]
byteorder = "1"
getopts = "*"
log = "*"
num-derive = "*"
num-traits = "*"
text_io = "*"
simplelog = "^0.5.0"
